### PR TITLE
Add parsing of M3U8ExtXKey

### PR DESCRIPTION
**Pull request by PierrePerrin**
Hi,

I've add the ability to parse the M3U8ExtXKey.
This could be useful for parsing content identifier for protected content such as FairPlay or HLS-AES content.

Thank you.

### CODE REVIEW

**Comment by wolfcon** [comment]
Add a m3u8 file example (just like 769.m3u8 in demo project) for demo to test it plz. 

`
PS:
thx for PR. 
rebase your code and collect it
`

**Comment by PierrePerrin** [comment]
Hi, I've just added an example of encrypted file into the demo project directory.

**Comment by wolfcon** [comment]
My man. More detail should be concerned with multi-key.

See this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:7794
#EXT-X-TARGETDURATION:15
 
#EXT-X-KEY:METHOD=AES-128,URI="https://priv.example.com/key.php?r=52"
 
#EXTINF:2.833,
http://media.example.com/fileSequence52-A.ts
#EXTINF:15.0,
http://media.example.com/fileSequence52-B.ts
#EXTINF:13.333,
http://media.example.com/fileSequence52-C.ts
 
#EXT-X-KEY:METHOD=AES-128,URI="https://priv.example.com/key.php?r=53"
 
#EXTINF:15.0,
http://media.example.com/fileSequence53-A.ts
```

There is a circumstance that has more than one key in M3U8 file.
```objective-c
@interface M3U8MediaPlaylist : NSObject

@property (readonly, nonatomic, strong) M3U8ExtXKey *key;
```
The property should not be handled like this. 😎

**Comment by PierrePerrin** [comment]
Hi, 

I've removed the parsing of the M3U8ExtXKey and added M3U8ExtXSessionKey parsing directly in the master playlist.

Thanks

**Comment by wolfcon** [comment]
Thx for your contribution.🎉
I will merge these and modify some other things once I come back from vacation.

**Comment by wolfcon** [comment]
already solved thx man

**Comment by wolfcon** [comment]
@PierrePerrin hello. I've refactored X-Key & X-SessionKey function.
X-Key & X-SessionKey are both supported by M3U8Kit.

**Pull request merged**
